#!/usr/bin/env bash

DOTFILES_ROOT="`pwd`"

# Setting up the VIM Files

ln -sf $DOTFILES_ROOT/vim/gvimrc $HOME/.gvimrc

ln -sf $DOTFILES_ROOT/vim/vimrc $HOME/.vimrc

ln -sf $DOTFILES_ROOT/vim $HOME/.vim

ln -sf $DOTFILES_ROOT/tmux/tmux.conf $HOME/.tmux.conf

ln -sf $DOTFILES_ROOT/oh-my-zsh/ $HOME/.oh-my-zsh

mkdir -p ~/.config/htop/ && ln -sf $DOTFILES_ROOT/htop/htopc/ $HOME/.config/htop/htopc


# OSX Specific
#if [ "$(uname -s)" == "Darwin" ]
#then
#  echo "Installing OSX Specific Configuration"
#  source $DOTFILES_ROOT/osx/set-defaults.sh
#fi

if [ "$(uname -s)" == "Linux" ]
then
    echo "Installing Linux Specific Configuration"
    echo "alias pbcopy=\"xclip -selection clipboard\"" >> ~/.bash_profile
    echo "alias pbpaste=\"xclip -selection clipboard -o\"" >> ~/.bash_profile
fi

# Set vim as the global git diff tool
if git --version > /dev/null 2>&1; then
    git config --global diff.tool vimdiff
    git config --global merge.tool vimdiff
fi
