#!/usr/bin/env bash

ln -sfn .bash_profile $HOME/.bash_profile

ln -sfn .bash_logout $HOME/.bash_logout

ln -sfn .bash_aliases $HOME/.bash_aliases

ln -sfn .bash_functions $HOME/.bash_functions

ln -sfn .zshrc $HOME/.zshrc

ln -sfn vim/gvimrc $HOME/.gvimrc

ln -sfn vim/vimrc $HOME/.vimrc

ln -sfn vim/ $HOME/.vim

ln -sfn nvim/ $HOME/.config/nvim

ln -sfn tmux/tmux.conf $HOME/.tmux.conf

ln -sfn mysql/my.cnf $HOME/.my.cnf

ln -sfn oh-my-zsh/ $HOME/.oh-my-zsh

ln -sfn htop/ $HOME/.config/htop

ln -sfn gitconfig/ $HOME/.gitconfig

git config --global include.path $HOME/.gitconfig
