" Copy or symlink to ~/.vimrc or ~/_vimrc.

set nocompatible                  " Must come first because it changes other options.

execute pathogen#infect()
call pathogen#helptags() 		  " generate helptags for everything in ‘runtimepath’

syntax enable                     " Turn on syntax highlighting.
syntax on						  " Turn on syntax highlighting.
filetype plugin indent on         " Turn on file type detection.

set omnifunc=syntaxcomplete#Complete

runtime macros/matchit.vim        " Load the matchit plugin.

set autoindent                    " set auto indent
set ts=2                          " set indent to 2 spaces
set tabstop=2                     " Global tab width.
set nowrap
set shiftwidth=2
set expandtab                     " Use spaces instead of tabs
" set relativenumber              " show relative line numbers
set showcmd                       " Display incomplete commands.
set showmode                      " Display the mode you're in.
set showmatch                     " show bracket matches
set backspace=indent,eol,start    " Intuitive backspacing.
set hidden                        " Handle multiple buffers better.
set mouse=a                       " enable mouse support
set wildmenu                      " Enhanced command line completion.
set wildmode=list:longest         " Complete files like a shell.
set ignorecase                    " Case-insensitive searching.
set smartcase                     " But case-sensitive if expression contains a capital letter.
set number                        " Show line numbers.
set ruler                         " Show cursor position.
set incsearch                     " Highlight matches as you type.
set hlsearch                      " Highlight matches.
set scrolloff=5                   " Show 3 lines of context around the cursor.
set title                         " Set the terminal's title
set visualbell                    " No beeping.
set nobackup                      " Don't make a backup before overwriting a file.
set nowritebackup                 " And again.
set directory=$HOME/.vim/tmp//,.  " Keep swap files in one location
set noswapfile                    " Don't make any swap files
set laststatus=2                  " Show the status line all the time
set statusline=[%n]\ %<%.99f\ %h%w%m%r%y\ %{fugitive#statusline()}\ %{exists('*CapsLockStatusline')?CapsLockStatusline():''}%=%-16(\ %l,%c-%v\ %)%P


" Or use vividchalk
" colorscheme blackboard

set t_Co=256

colorscheme jules

let html_no_rendering=1

" highlight the status bar when in insert mode
"if version >= 700
"  au InsertEnter * hi StatusLine ctermfg=235 ctermbg=2
"  au InsertLeave * hi StatusLine ctermbg=240 ctermfg=12
"endif

" Tab mappings.
map <leader>tt :tabnew<cr>
map <leader>te :tabedit
map <leader>tc :tabclose<cr>
map <leader>to :tabonly<cr>
map <leader>tn :tabnext<cr>
map <leader>tp :tabprevious<cr>
map <leader>tf :tabfirst<cr>
map <leader>tl :tablast<cr>
map <leader>tm :tabmove

nnoremap <silent> [b :bprevious<CR>	
nnoremap <silent> ]b :bnext<CR>    
nnoremap <silent> [B :bfirst<CR>   
nnoremap <silent> ]B :blast<CR>    

" Mapping for NERDTree
map <F2> :NERDTreeToggle<CR>

" HTML Tools
map notags :%s#<\_.\{-1,}>##g<cr>

" Ruby Tools
" map <leader>r :!ruby %<cr>
" map <leader>r :new <bar> !ruby % 

" Automatic fold settings for specific files. Uncomment to use.
autocmd FileType ruby setlocal foldmethod=syntax
autocmd FileType css  setlocal foldmethod=indent shiftwidth=2 tabstop=2

" Handling reformatting of XML:
" http://ku1ik.com/2011/09/08/formatting-xml-in-vim-with-indent-command.s#<\_.\{-1,}>##g
autocmd FileType xml setlocal equalprg=xmllint\ --format\ --recover\ -\ 2>/dev/null


let NERDTreeShowHidden=1
let NERDTreeIgnore = ['\.DS_Store$']
autocmd VimEnter * NERDTree

augroup ColorcolumnOnlyInInsertMode
  autocmd!
  autocmd InsertEnter * setlocal colorcolumn=80
  autocmd InsertLeave * setlocal colorcolumn=0
augroup END

" Hiding concealment (inverted commas in JSON)
let g:vim_json_syntax_conceal = 0

